dist: focal
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: NmyFaUYlbbxD/zLSn5gOR4atWPao/LuXfbqwrKIJMnUvbPrdqmXI7G7lXzF1p1xHpOzAZdgaGxUYICsqAuxP0dlUd65LXq1KwFQK2Au6QD3yZURqNzOGQHVHLFWEi/rhyBEVMWC1hsGJfr2iDcBMCtmq2Z4kpEoyleM+2mEpIUVbR5RtpcruJ8pEW0z8gffv23G837X7egGJX3zz9SVVaWNpfcqkDj3Mef6NEPVtb1dY2ME0BVjRzt4q93bvw9sncHzV7PfzY4ecvOSwbWdrq3HhLqKS0Tkr5DcPp3HdTVxquz6bJGkArUQ9OoPeLdbSMkv3sOGW2ujqVClv+fZ1uFXVmiew6RMULS85TUdmwHNK3nhlsGTb+K6DKqyxPb70uWdTVRhchsy0uGw/b7zGZPY85Nl5PjShSaO+euTLJWP6NmmkU2TMLUzDpZBum15eeNUZ1mbTf8WyGUAGfaRkuNMjpZIqAHJwUgy2U+4Lytf6jgHChFCHpZCzU3LuIvHQKjP1M87iTTMwHaPQR7j+ErGBmwP8zBrTlNe1RQ+ldp+5pyHU3a4jeg3+eNYgnVOStQ6j+/1pX/BRr/4ujzlCtlzhzYSM/C5gCk0xVffDruvTpQ4b/Y0HM8UKeT27kC2mODUWkQsIGGkGWEkXZpD8Wa7lu7wKc8+bhluWwOtuEXg=
